[server]
# Configuration du serveur Streamlit
maxUploadSize = 3000  # Limite de téléchargement augmentée à 3000 MB

[theme]
# Personnalisation du thème (optionnel)
primaryColor = "#4CAF50"  # Vert pour l'ambiance agricole
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
